### ISSUE TITLE
namespace in vars (or default) missing

### ISSUE THREAD

**Issue by MarcoPalomo** [rafaelmnatali/k8s-gcp#7]
Hi,
I think the namespace variable name is missing.

**Comment by rafaelmnatali** [comment]
Hi @MarcoPalomo thanks for opening this issue.

Could you please explain the error? Where is the `namespace` variable missing.

**Comment by MarcoPalomo** [comment]
In the vars (or default/main.yml file). It's resolved. Thank you

Le jeu. 27 avr. 2023, 16:25, Rafael Natali ***@***.***> a
écrit :
